---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1662612/public_html/pwa
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp sw.js $DEPLOYPATH